export const moroccanCities: LabeledValue<MoroccanCity> = [
  { label: "Casablanca", value: "casablanca" },
  { label: "Rabat", value: "rabat" },
  { label: "Fes", value: "fes" },
  { label: "Marrakech", value: "marrakech" },
  { label: "Tangier", value: "tangier" },
  { label: "Agadir", value: "agadir" },
  { label: "Meknes", value: "meknes" },
  { label: "Oujda", value: "oujda" },
  { label: "Kenitra", value: "kenitra" },
  { label: "Tetouan", value: "tetouan" },
  { label: "Safi", value: "safi" },
  { label: "El Jadida", value: "el-jadida" },
  { label: "Beni Mellal", value: "beni-mellal" },
  { label: "Nador", value: "nador" },
  { label: "Taza", value: "taza" },
  { label: "Khouribga", value: "khouribga" },
  { label: "Mohammedia", value: "mohammedia" },
  { label: "Khemisset", value: "khemisset" },
  { label: "Larache", value: "larache" },
  { label: "Berrechid", value: "berrechid" },
  { label: "Taourirt", value: "taourirt" },
  { label: "Errachidia", value: "errachidia" },
  { label: "Taroudant", value: "taroudant" },
  { label: "Settat", value: "settat" },
  { label: "Sidi Kacem", value: "sidi-kacem" },
  { label: "Guelmim", value: "guelmim" },
  { label: "Ksar El Kebir", value: "ksar-el-kebir" },
  { label: "Tiznit", value: "tiznit" },
  { label: "Tan-Tan", value: "tan-tan" },
  { label: "Ouarzazate", value: "ouarzazate" },
  { label: "Sidi Slimane", value: "sidi-slimane" },
  { label: "Youssoufia", value: "youssoufia" },
  { label: "Skhirat", value: "skhirat" },
  { label: "Midelt", value: "midelt" },
  { label: "Azrou", value: "azrou" },
  { label: "Drarga", value: "drarga" },
  { label: "Berkane", value: "berkane" },
  { label: "Sefrou", value: "sefrou" },
  { label: "Ait Melloul", value: "ait-melloul" },
  { label: "Lqliaa", value: "lqliaa" },
  { label: "Laayoune", value: "laayoune" },
  { label: "Dakhla", value: "dakhla" },
  { label: "Boujdour", value: "boujdour" },
  { label: "Smara", value: "smara" },
  { label: "Essaouira", value: "essaouira" },
  { label: "Chefchaouen", value: "chefchaouen" },
  { label: "Al Hoceima", value: "al-hoceima" },
  { label: "Ifrane", value: "ifrane" },
  { label: "Asilah", value: "asilah" },
  { label: "Zagora", value: "zagora" },
  { label: "Figuig", value: "figuig" },
  { label: "Tinghir", value: "tinghir" },
  { label: "Demnate", value: "demnate" },
  { label: "Boumalne Dades", value: "boumalne-dades" },
  { label: "Oulad Teima", value: "oulad-teima" },
  { label: "Sidi Bennour", value: "sidi-bennour" },
  { label: "Sidi Ifni", value: "sidi-ifni" },
  { label: "Tiflet", value: "tiflet" },
  { label: "Bouznika", value: "bouznika" },
  { label: "Sidi Yahya El Gharb", value: "sidi-yahya-el-gharb" },
  { label: "Ouazzane", value: "ouazzane" },
  { label: "Tata", value: "tata" },
  { label: "Goulmima", value: "goulmima" },
  { label: "Zemamra", value: "zemamra" },
  { label: "Had Kourt", value: "had-kourt" },
  { label: "Souk El Arbaa", value: "souk-el-arbaa" },
  { label: "Bir Lehlou", value: "bir-lehlou" },
  { label: "Ain Harrouda", value: "ain-harrouda" },
  { label: "Sidi Allal El Bahraoui", value: "sidi-allal-el-bahraoui" },
  { label: "Sidi Bouzid", value: "sidi-bouzid" },
  { label: "Sidi Rahhal", value: "sidi-rahhal" },
  { label: "Sidi Taibi", value: "sidi-taibi" },
  { label: "Sidi Yahya Zaer", value: "sidi-yahya-zaer" },
  { label: "Tarfaya", value: "tarfaya" },
  { label: "Temara", value: "temara" },
  { label: "Tichka", value: "tichka" },
  { label: "Tichla", value: "tichla" },
  { label: "Tiztoutine", value: "tiztoutine" },
  { label: "Zawyat Ahansal", value: "zawyat-ahansal" },
];

export const moroccanCitiesEnums = moroccanCities.map((city) => city.value) as [
  MoroccanCity,
  ...MoroccanCity[],
];
