import type { Metadata } from "next";
import { Geist, Cairo } from "next/font/google";
import "./globals.css";
import { notFound } from "next/navigation";
import { Locale, routing } from "@/i18n/routing";
import Providers from "@/components/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  const initFont =
    locale === "en"
      ? `${geistSans.className} ${cairo.variable}`
      : `${cairo.className} ${geistSans.variable}`;

  return (
    <html dir={locale === "ar" ? "rtl" : "ltr"} lang={locale}>
      <body className={`${initFont} text-secondary antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
